INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (1, '', '进行T01');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (2, '', '进行T02');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (3, 'order valid', '进行T03');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (4, 'order invalid', '结束');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (5, '', '进行T04');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (6, '', '进行T05');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (7, 'Approved', '进行T07/T08');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (8, 'N_Approved', '进行T06');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (9, '', '进行T04');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (10, 'hire purchase', '进行T09');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (11, 'Full payment', '进行T09');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (12, '', '进行T10');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (13, '', '进行T11');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (14, 'received', '进行T15');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (15, 'N_received', '进行T12');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (16, '', '进行T13');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (17, '', '进行T14');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (18, '', '结束');
INSERT INTO BPMN_implement (id, execute_condition, execute_action) VALUES (19, '', '结束');